### ISSUE TITLE
App Graphics

### ISSUE THREAD

**Issue by neynah** [kentonv/ssjekyll#6]
How's this? 
![hackercms-preview1](https://cloud.githubusercontent.com/assets/855341/9426404/dc61a77a-48f2-11e5-8dd5-9bbf23b85ef7.png)

**Comment by kentonv** [comment]
I like it!

**Comment by kentonv** [comment]
Are there SVGs for this?

**Comment by ocdtrekkie** [comment]
Can be closed.
