### ISSUE TITLE
App not available?

### ISSUE THREAD

**Issue by treyharris** [kentonv/ssjekyll#8]
I can't find this app on the [Sandstorm App Market](https://apps.sandstorm.io/). Is it meant to be self-installed, and if so can you provide instructions?

If there's another app better suited to serving a static Jekyll site, I can't find it.

**Comment by ocdtrekkie** [comment]
This is known as "Hacker CMS".

https://apps.sandstorm.io/app/nqmcqs9spcdpmqyuxemf0tsgwn8awfvswc58wgk375g4u25xv6yh

**Comment by kentonv** [comment]
Thanks for pointing out that the readme is ridiculously outdated! Fixed.
